# backend/tests/test_report.py
from app.pipeline import report


def _model():
    return report.ReportModel(
        title="Herbaflow Analysis — Curcuma longa L. and Type 2 Diabetes Mellitus, 2026-06-14",
        subtitle="Curcuma longa L. · Type 2 Diabetes Mellitus",
        about=[
            "Human-only (species 9606).",
            "Computational predictions to guide research, not clinical conclusions.",
        ],
        stages=[
            report.StageSection(
                n=8,
                name="Functional enrichment",
                finding=(
                    "The 17 shared targets are enriched for blood circulation "
                    "(28 terms, FDR < 0.05)."
                ),
                params=[
                    report.ParamRow(
                        "Correction",
                        "Benjamini-Hochberg FDR",
                        None,
                        "Multiple-testing correction.",
                    )
                ],
                sources=[report.SourceLink("g:Profiler", "https://biit.cs.ut.ee/gprofiler/")],
                figure="stage8_enrichment_BP.png",
                csv="stages/stage8_enrichment.csv",
                preview=None,
                notes=[],
            )
        ],
        provenance=[
            "Every compound, target, and pathway links back to the public database it came from."
        ],
        footer="Generated by Herbaflow — http://localhost:5173",
    )


def test_render_markdown_has_no_bare_result_count():
    md = report.render_markdown(_model())
    assert "Result count:" not in md


def test_render_markdown_links_sources_and_pointers():
    md = report.render_markdown(_model())
    assert "[g:Profiler](https://biit.cs.ut.ee/gprofiler/)" in md
    assert "stages/stage8_enrichment.csv" in md
    assert "## Stage 8 — Functional enrichment" in md
    assert md.rstrip().endswith("http://localhost:5173")


def test_humanize_value_enums_bools_lists():
    assert (
        report.humanize_value("network_type", "functional")
        == "functional associations (not just physical binding)"
    )
    assert report.humanize_value("correction", "fdr") == "Benjamini-Hochberg FDR"
    assert report.humanize_value("apply_veber", True) == "Yes"
    assert report.humanize_value("sources", ["GO:BP", "KEGG"]) == "GO biological process, KEGG"


def test_format_int_thousands():
    assert report.fmt_num(2000) == "2,000"
    assert report.fmt_num(0.8651) == "0.8651"


def test_param_rows_pull_unit_and_description():
    rows = report.param_rows("adme", {"max_mw": 500, "apply_veber": True})
    mw = next(r for r in rows if r.label == "Max MW")
    assert mw.value == "500" and mw.unit == "Da" and "molecular weight" in mw.description.lower()
