# backend/tests/test_report.py
from app.pipeline import report


def _model():
    return report.ReportModel(
        title="Herbaflow Analysis — Curcuma longa L. and Type 2 Diabetes Mellitus, 2026-06-14",
        subtitle="Curcuma longa L. · Type 2 Diabetes Mellitus",
        about=[
            "Human-only (species 9606).",
            "Computational predictions to guide research, not clinical conclusions.",
        ],
        stages=[
            report.StageSection(
                n=8,
                name="Functional enrichment",
                finding=(
                    "The 17 shared targets are enriched for blood circulation "
                    "(28 terms, FDR < 0.05)."
                ),
                params=[
                    report.ParamRow(
                        "Correction",
                        "Benjamini-Hochberg FDR",
                        None,
                        "Multiple-testing correction.",
                    )
                ],
                sources=[report.SourceLink("g:Profiler", "https://biit.cs.ut.ee/gprofiler/")],
                figure="stage8_enrichment_BP.png",
                csv="stages/stage8_enrichment.csv",
                preview=None,
                notes=[],
            )
        ],
        provenance=[
            "Every compound, target, and pathway links back to the public database it came from."
        ],
        footer="Generated by Herbaflow — http://localhost:5173",
    )


def test_render_markdown_has_no_bare_result_count():
    md = report.render_markdown(_model())
    assert "Result count:" not in md


def test_render_markdown_links_sources_and_pointers():
    md = report.render_markdown(_model())
    assert "[g:Profiler](https://biit.cs.ut.ee/gprofiler/)" in md
    assert "stages/stage8_enrichment.csv" in md
    assert "## Stage 8: Functional enrichment" in md
    assert md.rstrip().endswith("http://localhost:5173")


def test_humanize_value_enums_bools_lists():
    assert (
        report.humanize_value("network_type", "functional")
        == "functional associations (not just physical binding)"
    )
    assert report.humanize_value("correction", "fdr") == "Benjamini-Hochberg FDR"
    assert report.humanize_value("apply_veber", True) == "Yes"
    assert report.humanize_value("sources", ["GO:BP", "KEGG"]) == "GO biological process, KEGG"


def test_format_int_thousands():
    assert report.fmt_num(2000) == "2,000"
    assert report.fmt_num(0.8651) == "0.8651"


def test_param_rows_pull_unit_and_description():
    rows = report.param_rows("adme", {"max_mw": 500, "apply_veber": True})
    mw = next(r for r in rows if r.label == "Max MW")
    assert mw.value == "500" and mw.unit == "Da" and "molecular weight" in mw.description.lower()


SR = {
    "1": {"count": 180, "compounds": []},
    "2": {"count": 175, "passed": [1] * 175, "filtered": [1] * 5},
    "3": {"count": 180, "targets": [], "coverage_pct": 70},
    "4": {"count": 911, "targets": []},
}


def test_s1_finding_selection_single():
    m = report.build_report_model(
        {"mode": "auto", "created_at": "x", "completed_at": "2026-06-14T0:0:0+00:00"},
        {"adme": {"max_mw": 500}},
        SR,
        {"plant": "Curcuma longa L.", "disease": "Type 2 Diabetes Mellitus"},
        input_modes={"plant": "selection", "disease": "selection"},
        frontend_url="http://localhost:5173",
        figures=[],
    )
    s1 = next(s for s in m.stages if s.n == 1)
    assert "Curcuma longa L." in s1.finding and "Result count" not in s1.finding


def test_s2_skip_adme_finding():
    sr = {**SR, "2": {"count": 180, "passed": [1] * 180, "filtered": []}}
    m = report.build_report_model(
        {"mode": "auto"},
        {"adme": {"skip_adme": True}},
        sr,
        {"plant": "P", "disease": "D"},
        input_modes={"plant": "selection", "disease": "selection"},
        frontend_url="u",
        figures=[],
    )
    s2 = next(s for s in m.stages if s.n == 2)
    assert "skipped" in s2.finding.lower()


def test_s6_reports_connected_and_isolated():
    sr = {
        "5": {"count": 17, "compound_target_count": 180, "disease_target_count": 911},
        "6": {
            "node_count": 17,
            "nodes": [{"gene_symbol": g} for g in ["A", "B", "C", "X"]],
            "edges": [{"source": "A", "target": "B"}, {"source": "B", "target": "C"}],
        },
        "7": {"hubs": [{"gene_symbol": "A", "mcc": 10}]},
        "8": {
            "terms": [
                {
                    "term_id": "GO:1",
                    "name": "blood circulation",
                    "source": "GO:BP",
                    "p_value": 1e-5,
                    "intersection": ["A", "B"],
                }
            ]
        },
    }
    m = report.build_report_model(
        {"mode": "auto"},
        {},
        sr,
        {"plant": "P", "disease": "D"},
        input_modes={},
        frontend_url="u",
        figures=[],
    )
    s6 = next(s for s in m.stages if s.n == 6)
    assert "3 interconnected" in s6.finding and "1 isolated" in s6.finding


def test_s8_finding_and_preview():
    sr = {
        "5": {"count": 17},
        "8": {
            "terms": [
                {
                    "term_id": "GO:1",
                    "name": "blood circulation",
                    "source": "GO:BP",
                    "p_value": 1e-5,
                    "intersection": ["A"] * 10,
                },
                {
                    "term_id": "KEGG:1",
                    "name": "x",
                    "source": "KEGG",
                    "p_value": 0.01,
                    "intersection": ["A"] * 3,
                },
            ]
        },
    }
    m = report.build_report_model(
        {"mode": "auto"},
        {},
        sr,
        {"plant": "P", "disease": "D"},
        input_modes={},
        frontend_url="u",
        figures=[],
    )
    s8 = next(s for s in m.stages if s.n == 8)
    assert "blood circulation" in s8.finding and s8.preview is not None


def test_s7_finding_and_preview_mcc():
    sr = {
        "5": {"count": 3},
        "7": {
            "hubs": [
                {"gene_symbol": "PPARG", "mcc": 50},
                {"gene_symbol": "AKT1", "mcc": 30},
                {"gene_symbol": "TP53", "mcc": 10},
            ]
        },
    }
    m = report.build_report_model(
        {"mode": "auto"},
        {},
        sr,
        {"plant": "P", "disease": "D"},
        input_modes={},
        frontend_url="u",
        figures=[],
    )
    s7 = next(s for s in m.stages if s.n == 7)
    # Finding must mention MCC and the top gene; no em dash
    assert "Maximal Clique Centrality" in s7.finding
    assert "PPARG" in s7.finding
    assert "—" not in s7.finding
    # Preview table must use "MCC score" column header
    assert s7.preview is not None
    assert s7.preview.columns[1] == "MCC score"
    # Rows are sorted by MCC descending; top row is PPARG with score 50
    assert s7.preview.rows[0] == ("PPARG", "50")


def test_report_preserves_no_version_checksum_honesty():
    # Software Lock §6.4: the provenance must keep the honest "we do not record the external
    # database release version" limitation. Guards the v2 coverage dropped when build_report
    # delegated to the report model.
    m = report.build_report_model(
        {"mode": "auto"},
        {},
        {"5": {"count": 1}},
        {"plant": "P", "disease": "D"},
        input_modes={},
        frontend_url="u",
        figures=[],
    )
    md = report.render_markdown(m)
    assert "## How to read these results" in md
    assert "not the exact release version" in md


def test_report_na_stage_finding_for_manual_targets():
    # manual_targets => stages 1-2 are not_applicable => their findings say so (not a count).
    m = report.build_report_model(
        {"mode": "auto"},
        {},
        {"3": {"count": 5}, "5": {"count": 1}},
        {"plant": "P", "disease": "D"},
        input_modes={"plant": "manual_targets"},
        frontend_url="u",
        figures=[],
    )
    s1 = next(s for s in m.stages if s.n == 1)
    assert "Not applicable" in s1.finding


def test_na_stage_section_has_empty_fields():
    # NA stages must have only the one-liner finding; all other fields are cleared.
    m = report.build_report_model(
        {"mode": "auto"},
        {"adme": {"max_mw": 500}},
        {"3": {"count": 5}, "5": {"count": 1}},
        {"plant": "P", "disease": "D"},
        input_modes={"plant": "manual_targets"},
        frontend_url="u",
        figures=[("stage1_compounds.png", True, "ok")],
    )
    for n in (1, 2):
        s = next(st for st in m.stages if st.n == n)
        assert s.params == [], f"stage {n}: params should be empty for NA"
        assert s.sources == [], f"stage {n}: sources should be empty for NA"
        assert s.figure is None, f"stage {n}: figure should be None for NA"
        assert s.csv is None, f"stage {n}: csv should be None for NA"
        assert s.preview is None, f"stage {n}: preview should be None for NA"
        assert "Not applicable" in s.finding, f"stage {n}: finding must be the one-liner"


def test_params_rendered_as_markdown_table():
    # Params block must be a markdown table, not a bullet list.
    md = report.render_markdown(_model())
    assert "| Parameter | Value | Description |" in md
    assert "| --- | --- | --- |" in md
    # Must NOT contain bullet-style param lines like "- **Correction:**"
    assert "- **Correction:**" not in md


def test_rendered_report_has_no_em_or_en_dashes_or_internal_jargon():
    # Export copy policy: no em/en dashes, no internal jargon in rendered output.
    m = report.build_report_model(
        {"mode": "auto"},
        {"adme": {"max_mw": 500}, "disease_targets": {"min_score": 0.5}},
        {
            "1": {"count": 180},
            "2": {"count": 175, "passed": [1] * 175, "filtered": [1] * 5},
            "3": {"count": 100, "targets": [], "coverage_pct": 70},
            "4": {"count": 900, "targets": []},
            "5": {"count": 17, "compound_target_count": 100, "disease_target_count": 900},
            "6": {"node_count": 17, "nodes": [], "edges": []},
            "7": {"hubs": [{"gene_symbol": "PPARG", "mcc": 42}]},
            "8": {
                "terms": [
                    {
                        "term_id": "GO:0008015",
                        "name": "blood circulation",
                        "source": "GO:BP",
                        "p_value": 1e-5,
                        "intersection": ["PPARG"],
                    }
                ]
            },
        },
        {"plant": "Curcuma longa L.", "disease": "Type 2 Diabetes"},
        input_modes={"plant": "selection", "disease": "selection"},
        frontend_url="",
        figures=[],
    )
    md = report.render_markdown(m)
    assert "—" not in md, "em dash found in rendered report"
    assert "–" not in md, "en dash found in rendered report"
    assert "§" not in md, "section sign (internal jargon) found in rendered report"
    assert "Lock" not in md, "'Lock' (internal jargon) found in rendered report"
    assert "ETL" not in md, "'ETL' (internal jargon) found in rendered report"
