// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ListDiseasesData, ListDiseasesResponse, ListPlantsData, ListPlantsResponse, CreateAnalysisData, CreateAnalysisResponse, CreateAnalysisError, GetAnalysisData, GetAnalysisResponse, GetAnalysisError, AdvanceAnalysisData, AdvanceAnalysisResponse, AdvanceAnalysisError, ValidateCompoundsData, ValidateCompoundsResponse, ValidateCompoundsError, HealthData, HealthResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Diseases
 */
export const listDiseases = <ThrowOnError extends boolean = false>(options?: Options<ListDiseasesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDiseasesResponse, unknown, ThrowOnError>({
        url: '/diseases',
        ...options
    });
};

/**
 * List Plants
 */
export const listPlants = <ThrowOnError extends boolean = false>(options?: Options<ListPlantsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListPlantsResponse, unknown, ThrowOnError>({
        url: '/plants',
        ...options
    });
};

/**
 * Create Analysis
 */
export const createAnalysis = <ThrowOnError extends boolean = false>(options: Options<CreateAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAnalysisResponse, CreateAnalysisError, ThrowOnError>({
        url: '/analyses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Analysis
 */
export const getAnalysis = <ThrowOnError extends boolean = false>(options: Options<GetAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAnalysisResponse, GetAnalysisError, ThrowOnError>({
        url: '/analyses/{analysis_id}',
        ...options
    });
};

/**
 * Advance Analysis
 */
export const advanceAnalysis = <ThrowOnError extends boolean = false>(options: Options<AdvanceAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AdvanceAnalysisResponse, AdvanceAnalysisError, ThrowOnError>({
        url: '/analyses/{analysis_id}/advance',
        ...options
    });
};

/**
 * Validate Compounds
 */
export const validateCompounds = <ThrowOnError extends boolean = false>(options: Options<ValidateCompoundsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ValidateCompoundsResponse, ValidateCompoundsError, ThrowOnError>({
        url: '/compounds/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Health
 * Liveness probe reporting service status.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthResponse, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};