// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ListDiseasesData, ListDiseasesResponse, ListPlantsData, ListPlantsResponse, CreateAnalysisData, CreateAnalysisResponse, CreateAnalysisError, GetAnalysisData, GetAnalysisResponse, GetAnalysisError, AdvanceAnalysisData, AdvanceAnalysisResponse, AdvanceAnalysisError, ResetFromData, ResetFromResponse, ResetFromError, EditStageData, EditStageResponse, EditStageError, ValidateCompoundsData, ValidateCompoundsResponse, ValidateCompoundsError, ValidateTargetsData, ValidateTargetsResponse2, ValidateTargetsError, ExportReportData, ExportReportError, ExportNetworkData, ExportNetworkError, ExportStagesData, ExportStagesError, ExportAllData, ExportAllError, ExportCtpNodesData, ExportCtpNodesError, ExportCtpEdgesData, ExportCtpEdgesError, ExportDockingData, ExportDockingError, ExportPpiNodesData, ExportPpiNodesError, ExportArtifactData, ExportArtifactError, HealthData, HealthResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Diseases
 */
export const listDiseases = <ThrowOnError extends boolean = false>(options?: Options<ListDiseasesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDiseasesResponse, unknown, ThrowOnError>({
        url: '/diseases',
        ...options
    });
};

/**
 * List Plants
 */
export const listPlants = <ThrowOnError extends boolean = false>(options?: Options<ListPlantsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListPlantsResponse, unknown, ThrowOnError>({
        url: '/plants',
        ...options
    });
};

/**
 * Create Analysis
 */
export const createAnalysis = <ThrowOnError extends boolean = false>(options: Options<CreateAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAnalysisResponse, CreateAnalysisError, ThrowOnError>({
        url: '/analyses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Analysis
 */
export const getAnalysis = <ThrowOnError extends boolean = false>(options: Options<GetAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAnalysisResponse, GetAnalysisError, ThrowOnError>({
        url: '/analyses/{analysis_id}',
        ...options
    });
};

/**
 * Advance Analysis
 */
export const advanceAnalysis = <ThrowOnError extends boolean = false>(options: Options<AdvanceAnalysisData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AdvanceAnalysisResponse, AdvanceAnalysisError, ThrowOnError>({
        url: '/analyses/{analysis_id}/advance',
        ...options
    });
};

/**
 * Reset From
 */
export const resetFrom = <ThrowOnError extends boolean = false>(options: Options<ResetFromData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResetFromResponse, ResetFromError, ThrowOnError>({
        url: '/analyses/{analysis_id}/reset-from/{stage}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Stage
 */
export const editStage = <ThrowOnError extends boolean = false>(options: Options<EditStageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<EditStageResponse, EditStageError, ThrowOnError>({
        url: '/analyses/{analysis_id}/stages/{stage}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Validate Compounds
 */
export const validateCompounds = <ThrowOnError extends boolean = false>(options: Options<ValidateCompoundsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ValidateCompoundsResponse, ValidateCompoundsError, ThrowOnError>({
        url: '/compounds/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Validate Targets
 */
export const validateTargets = <ThrowOnError extends boolean = false>(options: Options<ValidateTargetsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ValidateTargetsResponse2, ValidateTargetsError, ThrowOnError>({
        url: '/targets/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Export Report
 */
export const exportReport = <ThrowOnError extends boolean = false>(options: Options<ExportReportData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportReportError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/report.md',
        ...options
    });
};

/**
 * Export Network
 */
export const exportNetwork = <ThrowOnError extends boolean = false>(options: Options<ExportNetworkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportNetworkError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/network-and-docking.zip',
        ...options
    });
};

/**
 * Export Stages
 */
export const exportStages = <ThrowOnError extends boolean = false>(options: Options<ExportStagesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportStagesError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/stages.zip',
        ...options
    });
};

/**
 * Export All
 */
export const exportAll = <ThrowOnError extends boolean = false>(options: Options<ExportAllData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportAllError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/all-results.zip',
        ...options
    });
};

/**
 * Export Ctp Nodes
 */
export const exportCtpNodes = <ThrowOnError extends boolean = false>(options: Options<ExportCtpNodesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportCtpNodesError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/ctp-nodes.csv',
        ...options
    });
};

/**
 * Export Ctp Edges
 */
export const exportCtpEdges = <ThrowOnError extends boolean = false>(options: Options<ExportCtpEdgesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportCtpEdgesError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/ctp-edges.csv',
        ...options
    });
};

/**
 * Export Docking
 */
export const exportDocking = <ThrowOnError extends boolean = false>(options: Options<ExportDockingData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportDockingError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/docking.csv',
        ...options
    });
};

/**
 * Export Ppi Nodes
 */
export const exportPpiNodes = <ThrowOnError extends boolean = false>(options: Options<ExportPpiNodesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportPpiNodesError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/stage6_ppi_nodes.csv',
        ...options
    });
};

/**
 * Export Artifact
 * One artifact by its deterministic filename — serves both the per-stage/graph CSVs (e.g.
 * ``stage5_overlap.csv``) and the rendered chart PNGs (e.g. ``ctp-network.png``,
 * ``stage5_venn.png``). The set of valid filenames is the assembled network+stage allowlist — an
 * unknown artifact, or a chart that could not be drawn (None, conditional-PNG rule), 404s, so the
 * path segment can never address an arbitrary file (Software §8). Declared last, so the explicit
 * ``.zip`` / ``.md`` / ``.csv`` routes above still win.
 */
export const exportArtifact = <ThrowOnError extends boolean = false>(options: Options<ExportArtifactData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExportArtifactError, ThrowOnError>({
        url: '/analyses/{analysis_id}/export/{filename}',
        ...options
    });
};

/**
 * Health
 * Liveness probe reporting service status.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthResponse, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};