// This file is auto-generated by @hey-api/openapi-ts

export type AnalysisCreate = {
    analysis_name?: string | null;
    plant_ids: Array<string>;
    disease_id: string;
    mode?: Mode;
};

export type AnalysisRead = {
    analysis_id: string;
    analysis_name: string | null;
    disease_id: string | null;
    mode: Mode;
    status: string | null;
    current_stage: number | null;
    stage_results: {
        [key: string]: unknown;
    };
    created_at: string | null;
    completed_at: string | null;
    expires_at: string | null;
    error_message: string | null;
};

export type CompoundInput = {
    type?: ('smiles' | 'inchikey') | null;
    value: string;
};

export type DiseaseRead = {
    disease_id: string;
    canonical_key: string;
    disease_name: string | null;
    ontology_id: string | null;
    ontology_source: string | null;
    source_url: string | null;
    retrieved_at: string | null;
};

export type FailedInput = {
    value: string;
    reason: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Mode = 'auto' | 'guided';

export type PlantRead = {
    plant_id: string;
    canonical_key: string;
    canonical_scientific_name: string | null;
    family_name: string | null;
};

export type ResolvedCompound = {
    compound_id: string;
    canonical_key: string;
    canonical_name: string | null;
    validation_status: string;
};

export type ValidateRequest = {
    inputs: Array<CompoundInput>;
};

export type ValidateResponse = {
    resolved: Array<ResolvedCompound>;
    failed: Array<FailedInput>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListDiseasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/diseases';
};

export type ListDiseasesResponses = {
    /**
     * Successful Response
     */
    200: Array<DiseaseRead>;
};

export type ListDiseasesResponse = ListDiseasesResponses[keyof ListDiseasesResponses];

export type ListPlantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plants';
};

export type ListPlantsResponses = {
    /**
     * Successful Response
     */
    200: Array<PlantRead>;
};

export type ListPlantsResponse = ListPlantsResponses[keyof ListPlantsResponses];

export type CreateAnalysisData = {
    body: AnalysisCreate;
    path?: never;
    query?: never;
    url: '/analyses';
};

export type CreateAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisError = CreateAnalysisErrors[keyof CreateAnalysisErrors];

export type CreateAnalysisResponses = {
    /**
     * Successful Response
     */
    202: AnalysisRead;
};

export type CreateAnalysisResponse = CreateAnalysisResponses[keyof CreateAnalysisResponses];

export type GetAnalysisData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}';
};

export type GetAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisError = GetAnalysisErrors[keyof GetAnalysisErrors];

export type GetAnalysisResponses = {
    /**
     * Successful Response
     */
    200: AnalysisRead;
};

export type GetAnalysisResponse = GetAnalysisResponses[keyof GetAnalysisResponses];

export type AdvanceAnalysisData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/advance';
};

export type AdvanceAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdvanceAnalysisError = AdvanceAnalysisErrors[keyof AdvanceAnalysisErrors];

export type AdvanceAnalysisResponses = {
    /**
     * Successful Response
     */
    200: AnalysisRead;
};

export type AdvanceAnalysisResponse = AdvanceAnalysisResponses[keyof AdvanceAnalysisResponses];

export type ValidateCompoundsData = {
    body: ValidateRequest;
    path?: never;
    query?: never;
    url: '/compounds/validate';
};

export type ValidateCompoundsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateCompoundsError = ValidateCompoundsErrors[keyof ValidateCompoundsErrors];

export type ValidateCompoundsResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateCompoundsResponse = ValidateCompoundsResponses[keyof ValidateCompoundsResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};