// This file is auto-generated by @hey-api/openapi-ts

export type AnalysisCreate = {
    analysis_name?: string | null;
    plant_input_mode?: PlantInputMode;
    disease_input_mode?: DiseaseInputMode;
    plant_ids?: Array<string>;
    disease_id?: string | null;
    mode?: Mode;
    manual_compound_ids?: Array<string>;
    manual_target_ids?: Array<string>;
    manual_disease_target_ids?: Array<string>;
    plant_label?: string | null;
    disease_label?: string | null;
    /**
     * Per-group parameter overrides for any pipeline group (adme / target / disease_targets / ppi / hub_genes / enrichment); validated against the contract hard bounds at create, merged over the group defaults, and frozen as the run baseline.
     */
    parameters?: {
        [key: string]: {
            [key: string]: unknown;
        };
    } | null;
};

/**
 * Lean per-run shape for the recent-runs list.
 *
 * Deliberately omits ``stage_results`` (the heavy per-stage tables).
 * ``parameters`` is kept — it carries ``input_modes`` / ``labels`` / ``plant_ids``;
 * its size is bounded by the entity caps.
 */
export type AnalysisListItem = {
    analysis_id: string;
    analysis_name: string | null;
    status: string | null;
    current_stage: number | null;
    created_at: string | null;
    completed_at: string | null;
    disease_id: string | null;
    parameters?: {
        [key: string]: unknown;
    };
};

export type AnalysisRead = {
    analysis_id: string;
    analysis_name: string | null;
    disease_id: string | null;
    mode: Mode;
    status: string | null;
    current_stage: number | null;
    parameters?: {
        [key: string]: unknown;
    };
    stage_results: {
        [key: string]: unknown;
    };
    progress?: ProgressRead | null;
    created_at: string | null;
    completed_at: string | null;
    expires_at: string | null;
    error_message: string | null;
    /**
     * Per-stage entry-mode state (``computed``/``user_provided``/``not_applicable``) derived
     * from the run's ``input_modes`` via the canonical matrix. This is the entry-mode-INTENDED
     * state for the FE (greyed N/A stages + the "provided by you" badge), distinct from the
     * presentational ``stage_results[n].state`` — which the durable edit layer also flips to
     * ``user_provided`` when a *computed* entity stage is merely edited. A run with no
     * ``input_modes`` (legacy / all-selection) yields all ``computed``.
     */
    readonly stage_state: {
        [key: string]: string;
    };
};

export type CompoundInput = {
    type?: ('smiles' | 'inchikey') | null;
    value: string;
};

export type CtpGraph = {
    nodes: Array<CtpGraphNode>;
    edges: Array<CtpGraphEdge>;
};

export type CtpGraphEdge = {
    source: string;
    target: string;
    interaction: string;
    prediction_method: string;
    p_value: string;
};

export type CtpGraphNode = {
    id: string;
    label: string;
    type: string;
    inchikey: string;
    smiles: string;
    uniprot_accession: string;
    is_hub: string;
    source: string;
};

export type DiseaseInputMode = 'selection' | 'manual_disease_targets';

export type DiseaseRead = {
    disease_id: string;
    canonical_key: string;
    disease_name: string | null;
    ontology_id: string | null;
    ontology_source: string | null;
    source_url: string | null;
    retrieved_at: string | null;
    matched_alias?: string | null;
};

export type FailedInput = {
    value: string;
    reason: string;
    line?: number | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Mode = 'auto' | 'guided';

export type PlantInputMode = 'selection' | 'manual_compounds' | 'manual_targets';

export type PlantRead = {
    plant_id: string;
    canonical_key: string;
    canonical_scientific_name: string | null;
    family_name: string | null;
    matched_alias?: string | null;
};

/**
 * Live per-item progress for a running stage (Stage 2 or Stage 3 only).
 */
export type ProgressRead = {
    stage: number;
    processed: number;
    total: number;
};

/**
 * Body for POST /analyses/{id}/reset-from/{stage}.
 *
 * ``parameters`` is a stage-keyed map of ADME param overrides, e.g.
 * ``{"2": {"max_violations": 0}}``.  Only the entry matching the target
 * stage is extracted and forwarded to the service.
 */
export type ResetFromRequest = {
    parameters?: {
        [key: string]: {
            [key: string]: unknown;
        };
    } | null;
};

export type ResolvedCompound = {
    compound_id: string;
    canonical_key: string;
    canonical_name: string | null;
    validation_status: string;
};

export type ResolvedTarget = {
    target_id: string;
    canonical_key: string;
    gene_symbol: string | null;
    uniprot_accession: string | null;
    validation_status: string;
};

/**
 * Body for POST /analyses/{id}/stages/{stage}/edit.
 */
export type StageEditRequest = {
    add?: Array<string>;
    remove?: Array<string>;
};

export type TargetInput = {
    type?: ('symbol' | 'uniprot') | null;
    value: string;
};

export type ValidateRequest = {
    inputs: Array<CompoundInput>;
};

export type ValidateResponse = {
    resolved: Array<ResolvedCompound>;
    failed: Array<FailedInput>;
};

export type ValidateTargetsRequest = {
    inputs: Array<TargetInput>;
};

export type ValidateTargetsResponse = {
    resolved: Array<ResolvedTarget>;
    failed: Array<FailedInput>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListDiseasesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term (canonical name or alias)
         */
        q?: string | null;
        /**
         * Maximum number of results to return
         */
        limit?: number;
        /**
         * Number of results to skip
         */
        offset?: number;
    };
    url: '/diseases';
};

export type ListDiseasesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDiseasesError = ListDiseasesErrors[keyof ListDiseasesErrors];

export type ListDiseasesResponses = {
    /**
     * Successful Response
     */
    200: Array<DiseaseRead>;
};

export type ListDiseasesResponse = ListDiseasesResponses[keyof ListDiseasesResponses];

export type ListPlantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term (canonical name or alias)
         */
        q?: string | null;
        /**
         * Maximum number of results to return
         */
        limit?: number;
        /**
         * Number of results to skip
         */
        offset?: number;
    };
    url: '/plants';
};

export type ListPlantsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPlantsError = ListPlantsErrors[keyof ListPlantsErrors];

export type ListPlantsResponses = {
    /**
     * Successful Response
     */
    200: Array<PlantRead>;
};

export type ListPlantsResponse = ListPlantsResponses[keyof ListPlantsResponses];

export type ListAnalysesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/analyses';
};

export type ListAnalysesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAnalysesError = ListAnalysesErrors[keyof ListAnalysesErrors];

export type ListAnalysesResponses = {
    /**
     * Successful Response
     */
    200: Array<AnalysisListItem>;
};

export type ListAnalysesResponse = ListAnalysesResponses[keyof ListAnalysesResponses];

export type CreateAnalysisData = {
    body: AnalysisCreate;
    headers?: {
        'Idempotency-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/analyses';
};

export type CreateAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisError = CreateAnalysisErrors[keyof CreateAnalysisErrors];

export type CreateAnalysisResponses = {
    /**
     * Successful Response
     */
    202: AnalysisRead;
};

export type CreateAnalysisResponse = CreateAnalysisResponses[keyof CreateAnalysisResponses];

export type DeleteAnalysisData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}';
};

export type DeleteAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisError = DeleteAnalysisErrors[keyof DeleteAnalysisErrors];

export type DeleteAnalysisResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAnalysisResponse = DeleteAnalysisResponses[keyof DeleteAnalysisResponses];

export type GetAnalysisData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}';
};

export type GetAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisError = GetAnalysisErrors[keyof GetAnalysisErrors];

export type GetAnalysisResponses = {
    /**
     * Successful Response
     */
    200: AnalysisRead;
};

export type GetAnalysisResponse = GetAnalysisResponses[keyof GetAnalysisResponses];

export type AdvanceAnalysisData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/advance';
};

export type AdvanceAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdvanceAnalysisError = AdvanceAnalysisErrors[keyof AdvanceAnalysisErrors];

export type AdvanceAnalysisResponses = {
    /**
     * Successful Response
     */
    202: AnalysisRead;
};

export type AdvanceAnalysisResponse = AdvanceAnalysisResponses[keyof AdvanceAnalysisResponses];

export type ResetFromData = {
    body: ResetFromRequest;
    path: {
        analysis_id: string;
        stage: number;
    };
    query?: never;
    url: '/analyses/{analysis_id}/reset-from/{stage}';
};

export type ResetFromErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetFromError = ResetFromErrors[keyof ResetFromErrors];

export type ResetFromResponses = {
    /**
     * Successful Response
     */
    202: AnalysisRead;
};

export type ResetFromResponse = ResetFromResponses[keyof ResetFromResponses];

export type EditStageData = {
    body: StageEditRequest;
    path: {
        analysis_id: string;
        stage: number;
    };
    query?: never;
    url: '/analyses/{analysis_id}/stages/{stage}/edit';
};

export type EditStageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditStageError = EditStageErrors[keyof EditStageErrors];

export type EditStageResponses = {
    /**
     * Successful Response
     */
    202: AnalysisRead;
};

export type EditStageResponse = EditStageResponses[keyof EditStageResponses];

export type ValidateCompoundsData = {
    body: ValidateRequest;
    path?: never;
    query?: never;
    url: '/compounds/validate';
};

export type ValidateCompoundsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateCompoundsError = ValidateCompoundsErrors[keyof ValidateCompoundsErrors];

export type ValidateCompoundsResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateCompoundsResponse = ValidateCompoundsResponses[keyof ValidateCompoundsResponses];

export type ValidateTargetsData = {
    body: ValidateTargetsRequest;
    path?: never;
    query?: never;
    url: '/targets/validate';
};

export type ValidateTargetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateTargetsError = ValidateTargetsErrors[keyof ValidateTargetsErrors];

export type ValidateTargetsResponses = {
    /**
     * Successful Response
     */
    200: ValidateTargetsResponse;
};

export type ValidateTargetsResponse2 = ValidateTargetsResponses[keyof ValidateTargetsResponses];

export type ExportReportData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/report.md';
};

export type ExportReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportReportError = ExportReportErrors[keyof ExportReportErrors];

export type ExportReportResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportNetworkData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/network-and-docking.zip';
};

export type ExportNetworkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportNetworkError = ExportNetworkErrors[keyof ExportNetworkErrors];

export type ExportNetworkResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportStagesData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/stages.zip';
};

export type ExportStagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportStagesError = ExportStagesErrors[keyof ExportStagesErrors];

export type ExportStagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportAllData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/all-results.zip';
};

export type ExportAllErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportAllError = ExportAllErrors[keyof ExportAllErrors];

export type ExportAllResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportCtpNodesData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/ctp-nodes.csv';
};

export type ExportCtpNodesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportCtpNodesError = ExportCtpNodesErrors[keyof ExportCtpNodesErrors];

export type ExportCtpNodesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportCtpEdgesData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/ctp-edges.csv';
};

export type ExportCtpEdgesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportCtpEdgesError = ExportCtpEdgesErrors[keyof ExportCtpEdgesErrors];

export type ExportCtpEdgesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportDockingData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/docking.csv';
};

export type ExportDockingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportDockingError = ExportDockingErrors[keyof ExportDockingErrors];

export type ExportDockingResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportPpiNodesData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/stage6_ppi_nodes.csv';
};

export type ExportPpiNodesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportPpiNodesError = ExportPpiNodesErrors[keyof ExportPpiNodesErrors];

export type ExportPpiNodesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCtpGraphData = {
    body?: never;
    path: {
        analysis_id: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/ctp-graph';
};

export type GetCtpGraphErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCtpGraphError = GetCtpGraphErrors[keyof GetCtpGraphErrors];

export type GetCtpGraphResponses = {
    /**
     * Successful Response
     */
    200: CtpGraph;
};

export type GetCtpGraphResponse = GetCtpGraphResponses[keyof GetCtpGraphResponses];

export type ExportArtifactData = {
    body?: never;
    path: {
        analysis_id: string;
        filename: string;
    };
    query?: never;
    url: '/analyses/{analysis_id}/export/{filename}';
};

export type ExportArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportArtifactError = ExportArtifactErrors[keyof ExportArtifactErrors];

export type ExportArtifactResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};