// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAnalysisCreate = z.object({
    analysis_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    plant_ids: z.array(z.string().uuid()).min(1).max(20),
    disease_id: z.string().uuid(),
    mode: z.enum([
        'auto',
        'guided'
    ]).optional(),
    manual_compound_ids: z.array(z.string().uuid()).optional()
});

export const zAnalysisRead = z.object({
    analysis_id: z.string().uuid(),
    analysis_name: z.union([
        z.string(),
        z.null()
    ]),
    disease_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    mode: z.enum([
        'auto',
        'guided'
    ]),
    status: z.union([
        z.string(),
        z.null()
    ]),
    current_stage: z.union([
        z.number().int(),
        z.null()
    ]),
    stage_results: z.object({}),
    created_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    completed_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    expires_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    error_message: z.union([
        z.string(),
        z.null()
    ])
});

export const zCompoundInput = z.object({
    type: z.union([
        z.enum([
            'smiles',
            'inchikey'
        ]),
        z.null()
    ]).optional(),
    value: z.string()
});

export const zDiseaseRead = z.object({
    disease_id: z.string().uuid(),
    canonical_key: z.string(),
    disease_name: z.union([
        z.string(),
        z.null()
    ]),
    ontology_id: z.union([
        z.string(),
        z.null()
    ]),
    ontology_source: z.union([
        z.string(),
        z.null()
    ]),
    source_url: z.union([
        z.string(),
        z.null()
    ]),
    retrieved_at: z.union([
        z.string().datetime(),
        z.null()
    ])
});

export const zFailedInput = z.object({
    value: z.string(),
    reason: z.string()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string(),
        input: z.unknown().optional(),
        ctx: z.object({}).optional()
    })).optional()
});

export const zMode = z.enum([
    'auto',
    'guided'
]);

export const zPlantRead = z.object({
    plant_id: z.string().uuid(),
    canonical_key: z.string(),
    canonical_scientific_name: z.union([
        z.string(),
        z.null()
    ]),
    family_name: z.union([
        z.string(),
        z.null()
    ])
});

export const zResolvedCompound = z.object({
    compound_id: z.string().uuid(),
    canonical_key: z.string(),
    canonical_name: z.union([
        z.string(),
        z.null()
    ]),
    validation_status: z.string()
});

export const zValidateRequest = z.object({
    inputs: z.array(zCompoundInput)
});

export const zValidateResponse = z.object({
    resolved: z.array(zResolvedCompound),
    failed: z.array(zFailedInput)
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.object({}).optional()
});

export const zListDiseasesResponse = z.array(zDiseaseRead);

export const zListPlantsResponse = z.array(zPlantRead);

export const zCreateAnalysisResponse = zAnalysisRead;

export const zGetAnalysisResponse = zAnalysisRead;

export const zAdvanceAnalysisResponse = zAnalysisRead;

export const zValidateCompoundsResponse = zValidateResponse;

export const zHealthResponse = z.object({});