// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAnalysisCreate = z.object({
    analysis_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    plant_input_mode: z.enum([
        'selection',
        'manual_compounds',
        'manual_targets'
    ]).optional(),
    disease_input_mode: z.enum([
        'selection',
        'manual_disease_targets'
    ]).optional(),
    plant_ids: z.array(z.string().uuid()).max(20).optional(),
    disease_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    mode: z.enum([
        'auto',
        'guided'
    ]).optional(),
    manual_compound_ids: z.array(z.string().uuid()).optional(),
    manual_target_ids: z.array(z.string().uuid()).optional(),
    manual_disease_target_ids: z.array(z.string().uuid()).optional(),
    plant_label: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    disease_label: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    parameters: z.union([
        z.object({}),
        z.null()
    ]).optional()
});

export const zAnalysisListItem = z.object({
    analysis_id: z.string().uuid(),
    analysis_name: z.union([
        z.string(),
        z.null()
    ]),
    status: z.union([
        z.string(),
        z.null()
    ]),
    current_stage: z.union([
        z.number().int(),
        z.null()
    ]),
    created_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    completed_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    disease_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    parameters: z.object({}).optional()
});

export const zAnalysisRead = z.object({
    analysis_id: z.string().uuid(),
    analysis_name: z.union([
        z.string(),
        z.null()
    ]),
    disease_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    mode: z.enum([
        'auto',
        'guided'
    ]),
    status: z.union([
        z.string(),
        z.null()
    ]),
    current_stage: z.union([
        z.number().int(),
        z.null()
    ]),
    parameters: z.object({}).optional(),
    stage_results: z.object({}),
    progress: z.union([
        z.object({
            stage: z.number().int(),
            processed: z.number().int(),
            total: z.number().int()
        }),
        z.null()
    ]).optional(),
    created_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    completed_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    expires_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    error_message: z.union([
        z.string(),
        z.null()
    ]),
    stage_state: z.object({}).readonly()
});

export const zCompoundInput = z.object({
    type: z.union([
        z.enum([
            'smiles',
            'inchikey'
        ]),
        z.null()
    ]).optional(),
    value: z.string()
});

export const zCtpGraph = z.object({
    nodes: z.array(z.object({
        id: z.string(),
        label: z.string(),
        type: z.string(),
        inchikey: z.string(),
        smiles: z.string(),
        uniprot_accession: z.string(),
        is_hub: z.string(),
        source: z.string()
    })),
    edges: z.array(z.object({
        source: z.string(),
        target: z.string(),
        interaction: z.string(),
        prediction_method: z.string(),
        p_value: z.string()
    }))
});

export const zCtpGraphEdge = z.object({
    source: z.string(),
    target: z.string(),
    interaction: z.string(),
    prediction_method: z.string(),
    p_value: z.string()
});

export const zCtpGraphNode = z.object({
    id: z.string(),
    label: z.string(),
    type: z.string(),
    inchikey: z.string(),
    smiles: z.string(),
    uniprot_accession: z.string(),
    is_hub: z.string(),
    source: z.string()
});

export const zDiseaseInputMode = z.enum([
    'selection',
    'manual_disease_targets'
]);

export const zDiseaseRead = z.object({
    disease_id: z.string().uuid(),
    canonical_key: z.string(),
    disease_name: z.union([
        z.string(),
        z.null()
    ]),
    ontology_id: z.union([
        z.string(),
        z.null()
    ]),
    ontology_source: z.union([
        z.string(),
        z.null()
    ]),
    source_url: z.union([
        z.string(),
        z.null()
    ]),
    retrieved_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    matched_alias: z.union([
        z.string(),
        z.null()
    ]).optional(),
    target_count: z.number().int().optional().default(0)
});

export const zFailedInput = z.object({
    value: z.string(),
    reason: z.string(),
    line: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string(),
        input: z.unknown().optional(),
        ctx: z.object({}).optional()
    })).optional()
});

export const zMode = z.enum([
    'auto',
    'guided'
]);

export const zPlantInputMode = z.enum([
    'selection',
    'manual_compounds',
    'manual_targets'
]);

export const zPlantRead = z.object({
    plant_id: z.string().uuid(),
    canonical_key: z.string(),
    canonical_scientific_name: z.union([
        z.string(),
        z.null()
    ]),
    family_name: z.union([
        z.string(),
        z.null()
    ]),
    matched_alias: z.union([
        z.string(),
        z.null()
    ]).optional(),
    compound_count: z.number().int().optional().default(0)
});

export const zProgressRead = z.object({
    stage: z.number().int(),
    processed: z.number().int(),
    total: z.number().int()
});

export const zResetFromRequest = z.object({
    parameters: z.union([
        z.object({}),
        z.null()
    ]).optional()
});

export const zResolvedCompound = z.object({
    compound_id: z.string().uuid(),
    canonical_key: z.string(),
    canonical_name: z.union([
        z.string(),
        z.null()
    ]),
    pubchem_cid: z.union([
        z.string(),
        z.null()
    ]).optional(),
    validation_status: z.string()
});

export const zResolvedTarget = z.object({
    target_id: z.string().uuid(),
    canonical_key: z.string(),
    gene_symbol: z.union([
        z.string(),
        z.null()
    ]),
    uniprot_accession: z.union([
        z.string(),
        z.null()
    ]),
    validation_status: z.string()
});

export const zStageEditRequest = z.object({
    add: z.array(z.string().uuid()).optional(),
    remove: z.array(z.string().uuid()).optional(),
    stp_compound_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    stp_target_ids: z.array(z.string().uuid()).optional()
});

export const zTargetInput = z.object({
    type: z.union([
        z.enum([
            'symbol',
            'uniprot'
        ]),
        z.null()
    ]).optional(),
    value: z.string()
});

export const zValidateRequest = z.object({
    inputs: z.array(zCompoundInput)
});

export const zValidateResponse = z.object({
    resolved: z.array(zResolvedCompound),
    failed: z.array(zFailedInput)
});

export const zValidateTargetsRequest = z.object({
    inputs: z.array(zTargetInput)
});

export const zValidateTargetsResponse = z.object({
    resolved: z.array(zResolvedTarget),
    failed: z.array(zFailedInput)
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.object({}).optional()
});

export const zListDiseasesResponse = z.array(zDiseaseRead);

export const zListPlantsResponse = z.array(zPlantRead);

export const zListAnalysesResponse = z.array(zAnalysisListItem);

export const zCreateAnalysisResponse = zAnalysisRead;

export const zDeleteAnalysisResponse = z.void();

export const zGetAnalysisResponse = zAnalysisRead;

export const zAdvanceAnalysisResponse = zAnalysisRead;

export const zResetFromResponse = zAnalysisRead;

export const zEditStageResponse = zAnalysisRead;

export const zValidateCompoundsResponse = zValidateResponse;

export const zValidateTargetsResponse2 = zValidateTargetsResponse;

export const zGetCtpGraphResponse = zCtpGraph;

export const zHealthResponse = z.object({});