/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as AnalysisIdIndexRouteImport } from './routes/analysis.$id.index'
import { Route as AnalysisIdStageRouteImport } from './routes/analysis.$id.$stage'

const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisIdIndexRoute = AnalysisIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisIdRoute,
} as any)
const AnalysisIdStageRoute = AnalysisIdStageRouteImport.update({
  id: '/$stage',
  path: '/$stage',
  getParentRoute: () => AnalysisIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/': typeof AnalysisIndexRoute
  '/analysis/$id/$stage': typeof AnalysisIdStageRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisIndexRoute
  '/analysis/$id/$stage': typeof AnalysisIdStageRoute
  '/analysis/$id': typeof AnalysisIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/': typeof AnalysisIndexRoute
  '/analysis/$id/$stage': typeof AnalysisIdStageRoute
  '/analysis/$id/': typeof AnalysisIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/analysis/$id'
    | '/analysis/'
    | '/analysis/$id/$stage'
    | '/analysis/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/analysis' | '/analysis/$id/$stage' | '/analysis/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/analysis/$id'
    | '/analysis/'
    | '/analysis/$id/$stage'
    | '/analysis/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$id/': {
      id: '/analysis/$id/'
      path: '/'
      fullPath: '/analysis/$id/'
      preLoaderRoute: typeof AnalysisIdIndexRouteImport
      parentRoute: typeof AnalysisIdRoute
    }
    '/analysis/$id/$stage': {
      id: '/analysis/$id/$stage'
      path: '/$stage'
      fullPath: '/analysis/$id/$stage'
      preLoaderRoute: typeof AnalysisIdStageRouteImport
      parentRoute: typeof AnalysisIdRoute
    }
  }
}

interface AnalysisIdRouteChildren {
  AnalysisIdStageRoute: typeof AnalysisIdStageRoute
  AnalysisIdIndexRoute: typeof AnalysisIdIndexRoute
}

const AnalysisIdRouteChildren: AnalysisIdRouteChildren = {
  AnalysisIdStageRoute: AnalysisIdStageRoute,
  AnalysisIdIndexRoute: AnalysisIdIndexRoute,
}

const AnalysisIdRouteWithChildren = AnalysisIdRoute._addFileChildren(
  AnalysisIdRouteChildren,
)

interface AnalysisRouteChildren {
  AnalysisIdRoute: typeof AnalysisIdRouteWithChildren
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisIdRoute: AnalysisIdRouteWithChildren,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
