// This file is auto-generated by @hey-api/openapi-ts

import { type Options, listDiseases, listPlants, listAnalyses, createAnalysis, getAnalysis, advanceAnalysis, resetFrom, editStage, validateCompounds, validateTargets, exportReport, exportNetwork, exportStages, exportAll, exportCtpNodes, exportCtpEdges, exportDocking, exportPpiNodes, exportArtifact, health } from '../sdk.gen';
import { queryOptions, infiniteQueryOptions, type InfiniteData } from '@tanstack/react-query';
import type { ListDiseasesData, ListDiseasesError, ListDiseasesResponse, ListPlantsData, ListPlantsError, ListPlantsResponse, ListAnalysesData, ListAnalysesError, ListAnalysesResponse, CreateAnalysisData, GetAnalysisData, AdvanceAnalysisData, ResetFromData, EditStageData, ValidateCompoundsData, ValidateTargetsData, ExportReportData, ExportNetworkData, ExportStagesData, ExportAllData, ExportCtpNodesData, ExportCtpEdgesData, ExportDockingData, ExportPpiNodesData, ExportArtifactData, HealthData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const listDiseasesQueryKey = (options?: Options<ListDiseasesData>) => createQueryKey('listDiseases', options);

export const listDiseasesOptions = (options?: Options<ListDiseasesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listDiseases({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listDiseasesQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = queryKey[0];
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listDiseasesInfiniteQueryKey = (options?: Options<ListDiseasesData>): QueryKey<Options<ListDiseasesData>> => createQueryKey('listDiseases', options, true);

export const listDiseasesInfiniteOptions = (options?: Options<ListDiseasesData>) => {
    return infiniteQueryOptions<ListDiseasesResponse, ListDiseasesError, InfiniteData<ListDiseasesResponse>, QueryKey<Options<ListDiseasesData>>, number | Pick<QueryKey<Options<ListDiseasesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListDiseasesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listDiseases({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listDiseasesInfiniteQueryKey(options)
    });
};

export const listPlantsQueryKey = (options?: Options<ListPlantsData>) => createQueryKey('listPlants', options);

export const listPlantsOptions = (options?: Options<ListPlantsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listPlants({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listPlantsQueryKey(options)
    });
};

export const listPlantsInfiniteQueryKey = (options?: Options<ListPlantsData>): QueryKey<Options<ListPlantsData>> => createQueryKey('listPlants', options, true);

export const listPlantsInfiniteOptions = (options?: Options<ListPlantsData>) => {
    return infiniteQueryOptions<ListPlantsResponse, ListPlantsError, InfiniteData<ListPlantsResponse>, QueryKey<Options<ListPlantsData>>, number | Pick<QueryKey<Options<ListPlantsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListPlantsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listPlants({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listPlantsInfiniteQueryKey(options)
    });
};

export const listAnalysesQueryKey = (options?: Options<ListAnalysesData>) => createQueryKey('listAnalyses', options);

export const listAnalysesOptions = (options?: Options<ListAnalysesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listAnalyses({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listAnalysesQueryKey(options)
    });
};

export const listAnalysesInfiniteQueryKey = (options?: Options<ListAnalysesData>): QueryKey<Options<ListAnalysesData>> => createQueryKey('listAnalyses', options, true);

export const listAnalysesInfiniteOptions = (options?: Options<ListAnalysesData>) => {
    return infiniteQueryOptions<ListAnalysesResponse, ListAnalysesError, InfiniteData<ListAnalysesResponse>, QueryKey<Options<ListAnalysesData>>, number | Pick<QueryKey<Options<ListAnalysesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListAnalysesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listAnalyses({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listAnalysesInfiniteQueryKey(options)
    });
};

export const createAnalysisQueryKey = (options: Options<CreateAnalysisData>) => createQueryKey('createAnalysis', options);

export const createAnalysisOptions = (options: Options<CreateAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createAnalysisQueryKey(options)
    });
};

export const getAnalysisQueryKey = (options: Options<GetAnalysisData>) => createQueryKey('getAnalysis', options);

export const getAnalysisOptions = (options: Options<GetAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAnalysisQueryKey(options)
    });
};

export const advanceAnalysisQueryKey = (options: Options<AdvanceAnalysisData>) => createQueryKey('advanceAnalysis', options);

export const advanceAnalysisOptions = (options: Options<AdvanceAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await advanceAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: advanceAnalysisQueryKey(options)
    });
};

export const resetFromQueryKey = (options: Options<ResetFromData>) => createQueryKey('resetFrom', options);

export const resetFromOptions = (options: Options<ResetFromData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resetFrom({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: resetFromQueryKey(options)
    });
};

export const editStageQueryKey = (options: Options<EditStageData>) => createQueryKey('editStage', options);

export const editStageOptions = (options: Options<EditStageData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await editStage({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: editStageQueryKey(options)
    });
};

export const validateCompoundsQueryKey = (options: Options<ValidateCompoundsData>) => createQueryKey('validateCompounds', options);

export const validateCompoundsOptions = (options: Options<ValidateCompoundsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await validateCompounds({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: validateCompoundsQueryKey(options)
    });
};

export const validateTargetsQueryKey = (options: Options<ValidateTargetsData>) => createQueryKey('validateTargets', options);

export const validateTargetsOptions = (options: Options<ValidateTargetsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await validateTargets({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: validateTargetsQueryKey(options)
    });
};

export const exportReportQueryKey = (options: Options<ExportReportData>) => createQueryKey('exportReport', options);

export const exportReportOptions = (options: Options<ExportReportData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportReport({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportReportQueryKey(options)
    });
};

export const exportNetworkQueryKey = (options: Options<ExportNetworkData>) => createQueryKey('exportNetwork', options);

export const exportNetworkOptions = (options: Options<ExportNetworkData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportNetwork({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportNetworkQueryKey(options)
    });
};

export const exportStagesQueryKey = (options: Options<ExportStagesData>) => createQueryKey('exportStages', options);

export const exportStagesOptions = (options: Options<ExportStagesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportStages({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportStagesQueryKey(options)
    });
};

export const exportAllQueryKey = (options: Options<ExportAllData>) => createQueryKey('exportAll', options);

export const exportAllOptions = (options: Options<ExportAllData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportAll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportAllQueryKey(options)
    });
};

export const exportCtpNodesQueryKey = (options: Options<ExportCtpNodesData>) => createQueryKey('exportCtpNodes', options);

export const exportCtpNodesOptions = (options: Options<ExportCtpNodesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportCtpNodes({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportCtpNodesQueryKey(options)
    });
};

export const exportCtpEdgesQueryKey = (options: Options<ExportCtpEdgesData>) => createQueryKey('exportCtpEdges', options);

export const exportCtpEdgesOptions = (options: Options<ExportCtpEdgesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportCtpEdges({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportCtpEdgesQueryKey(options)
    });
};

export const exportDockingQueryKey = (options: Options<ExportDockingData>) => createQueryKey('exportDocking', options);

export const exportDockingOptions = (options: Options<ExportDockingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportDocking({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportDockingQueryKey(options)
    });
};

export const exportPpiNodesQueryKey = (options: Options<ExportPpiNodesData>) => createQueryKey('exportPpiNodes', options);

export const exportPpiNodesOptions = (options: Options<ExportPpiNodesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportPpiNodes({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportPpiNodesQueryKey(options)
    });
};

export const exportArtifactQueryKey = (options: Options<ExportArtifactData>) => createQueryKey('exportArtifact', options);

export const exportArtifactOptions = (options: Options<ExportArtifactData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exportArtifact({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exportArtifactQueryKey(options)
    });
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

export const healthOptions = (options?: Options<HealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await health({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthQueryKey(options)
    });
};