// This file is auto-generated by @hey-api/openapi-ts

import { type Options, listDiseases, listPlants, createAnalysis, getAnalysis, advanceAnalysis, resetFrom, editStage, validateCompounds, health } from '../sdk.gen';
import { queryOptions } from '@tanstack/react-query';
import type { ListDiseasesData, ListPlantsData, CreateAnalysisData, GetAnalysisData, AdvanceAnalysisData, ResetFromData, EditStageData, ValidateCompoundsData, HealthData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const listDiseasesQueryKey = (options?: Options<ListDiseasesData>) => createQueryKey('listDiseases', options);

export const listDiseasesOptions = (options?: Options<ListDiseasesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listDiseases({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listDiseasesQueryKey(options)
    });
};

export const listPlantsQueryKey = (options?: Options<ListPlantsData>) => createQueryKey('listPlants', options);

export const listPlantsOptions = (options?: Options<ListPlantsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listPlants({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listPlantsQueryKey(options)
    });
};

export const createAnalysisQueryKey = (options: Options<CreateAnalysisData>) => createQueryKey('createAnalysis', options);

export const createAnalysisOptions = (options: Options<CreateAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createAnalysisQueryKey(options)
    });
};

export const getAnalysisQueryKey = (options: Options<GetAnalysisData>) => createQueryKey('getAnalysis', options);

export const getAnalysisOptions = (options: Options<GetAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAnalysisQueryKey(options)
    });
};

export const advanceAnalysisQueryKey = (options: Options<AdvanceAnalysisData>) => createQueryKey('advanceAnalysis', options);

export const advanceAnalysisOptions = (options: Options<AdvanceAnalysisData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await advanceAnalysis({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: advanceAnalysisQueryKey(options)
    });
};

export const resetFromQueryKey = (options: Options<ResetFromData>) => createQueryKey('resetFrom', options);

export const resetFromOptions = (options: Options<ResetFromData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await resetFrom({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: resetFromQueryKey(options)
    });
};

export const editStageQueryKey = (options: Options<EditStageData>) => createQueryKey('editStage', options);

export const editStageOptions = (options: Options<EditStageData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await editStage({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: editStageQueryKey(options)
    });
};

export const validateCompoundsQueryKey = (options: Options<ValidateCompoundsData>) => createQueryKey('validateCompounds', options);

export const validateCompoundsOptions = (options: Options<ValidateCompoundsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await validateCompounds({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: validateCompoundsQueryKey(options)
    });
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

export const healthOptions = (options?: Options<HealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await health({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthQueryKey(options)
    });
};